### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Coding-with-Adam**

### CODE REVIEW

**Comment by andrew-hossack** [comment]
Looks like we pushed a lot of changes at the same time. Would you be able to pull the new changes off `dev` to your local branch to resolve tings? @Coding-with-Adam

**Comment by andrew-hossack** [comment]
Gotta love the late night code sessions ☕

**Comment by Coding-with-Adam** [comment]
HI @andrew-hossack 
Take a look at what I did with [the readme](https://github.com/andrew-hossack/dash-tools/tree/Coding-with-Adam-testing-readme) last night. If you like it, I can redo it with the most recent dev version you made. If not, we can just delete it.

What I tried to do is delete example C (explaining how to build your app with csv sheet), and I incorporated that into example A. I like it because there are fewer examples. However, it might be too condense with too much info in part A. If you prefer the latest version of the readme with CSV app being its own part in example C, feel free to close the PR I made last night.

**Comment by andrew-hossack** [comment]
@Coding-with-Adam I like the idea of condensing the creating app examples, If you want to redo it with latest dev version that could be helpful.

I added a new example A for deploying and updating apps to Heroku, let me know what you think of that

**Comment by Coding-with-Adam** [comment]
Hi @andrew-hossack 
Sorry for the late response. It's been hectic with the Kansas City Chiefs webinar yesterday and debrief today. Great, I'll make sure to work off the most recent dev and update the readme.

**Comment by andrew-hossack** [comment]
No problem @Coding-with-Adam I've been busy with moving into my new place.

**Comment by andrew-hossack** [comment]
Seems like there isn't much left to do besides update these examples and make the new release. Should I try to have the post and articles updated this weekend?

**Comment by Coding-with-Adam** [comment]
> Seems like there isn't much left to do besides update these examples and make the new release. Should I try to have the post and articles updated this weekend?

yes, I agree, @andrew-hossack . Once you have the post and article updated, just email them to me and I'll look it over.

**Comment by Coding-with-Adam** [comment]
This made changes to the previous readme that is no longer relevant

**Pull request closed without merging**
