### PR TITLE
:lock: use non-root user in generated Dockerfile

### LINKED ISSUE #71: [Feature Request] Change created Dockerfiles to use a non-root user.
**Is your feature request related to a problem? Please describe.**
Dockerfiles generated by `dashtools docker --init` default to the base image default user (in this case root). Best practice is to run container processes as a non-root user.

**Describe the solution you'd like**
Update the process that generates Dockerfiles to create and use a non-root user.

**Describe alternatives you've considered**
Alternative would be to continue running as root user, but this is not advised and is also easy to prevent.

I will submit a PR to fix this Issue shortly.

### PR DESCRIPTION
**Pull request by jasonwashburn**
This PR updates `_write_dockerfile()` to create a Dockerfile which creates and uses a non-root user (`dash`). Additionally, I've added some testing for `dockerUtils.py`. 

Resolves #71 .

### CODE REVIEW

**Comment by jasonwashburn** [comment]
Looking at the pipeline test failure, and workflow it appears the reason the imports fail is because the package is never actually installed after it's built, and hence isn't included in the PYTHONPATH. Current tests seem to be working because of the try/catch block import that switches to using a relative import. Those could also be removed by adding the install step prior to running tests in CI, and doing an editable install from the directory during development `pip install -e .` 

I could add a quick fix under this branch if you'd like, or we could address the pipeline updates in a separate issue/PR branch.

**Comment by andrew-hossack** [comment]
> I could add a quick fix under this branch if you'd like, or we could address the pipeline updates in a separate issue/PR branch.

I've been trying to figure out the best way to get around having to use relative imports for local/package imports for testing in CI. If using editable install `pip install -e .` would fix this issue I'd definitely be open to looking over what changes you decide to make. Note that my use of relative imports _probably_ isn't standard or a best practice. Feel free to include changes in this PR, if that is easier!

Also changed your destination branch to dev for staging #76 Version 1.10.4

**Comment by andrew-hossack** [comment]
You may also notice that the current [unittest suite](https://github.com/andrew-hossack/dash-tools/tree/main/tests) is not being run, except for [this test](https://github.com/andrew-hossack/dash-tools/blob/main/tests/test_override.py) due to the relative import issue which I wasn't sure how to fix. Essentially the `_` character turns off those tests. I am planning on making a bigger push for more comprehensive unittesting, but would rather prioritize feature development first.

**Review by andrew-hossack — APPROVED** [review]
Lgtm! Pre-approved this for when unittests are "passing" (keep them just make them inactive here)

**Pull request merged**
